# Generated by Django 3.0 on 2020-12-17 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infog',
            name='i_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 5, 59, 45, 188954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='date_inp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 5, 59, 45, 188954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='search',
            name='d',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 5, 59, 45, 188954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 5, 59, 45, 187242, tzinfo=utc)),
        ),
    ]
