# Generated by Django 3.0 on 2020-12-17 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20201217_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infog',
            name='i_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 6, 48, 5, 151558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='date_inp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 6, 48, 5, 158788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='search',
            name='d',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 6, 48, 5, 158788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 6, 48, 5, 151558, tzinfo=utc)),
        ),
    ]
