# Generated by Django 3.0 on 2020-12-17 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20201217_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infog',
            name='i_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 7, 0, 26, 210838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='date_inp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 7, 0, 26, 210838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='search',
            name='d',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 7, 0, 26, 210838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 7, 0, 26, 210838, tzinfo=utc)),
        ),
    ]
