# Generated by Django 3.0 on 2020-12-17 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20201217_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infog',
            name='i_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 9, 26, 3, 909216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='date_inp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 9, 26, 3, 909216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='search',
            name='d',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 9, 26, 3, 909216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 9, 26, 3, 906603, tzinfo=utc)),
        ),
    ]
