# Generated by Django 3.0 on 2020-12-17 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20201217_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searc', models.CharField(max_length=1000, null=True)),
                ('d', models.DateTimeField(default=datetime.datetime(2020, 12, 17, 12, 56, 54, 134714, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='search',
        ),
        migrations.AlterField(
            model_name='infog',
            name='i_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 12, 56, 54, 134714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='date_inp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 12, 56, 54, 134714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 12, 56, 54, 134714, tzinfo=utc)),
        ),
    ]
