# Generated by Django 3.0 on 2020-12-18 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20201218_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='x_pts1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='x_pts2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='x_pts3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='x_pts4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='x_pts5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='y_pts1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='y_pts2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='y_pts3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='y_pts4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='y_pts5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infog',
            name='i_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 13, 40, 37, 881033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='date_inp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 13, 40, 37, 881033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='searchenter',
            name='d',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 13, 40, 37, 881033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_csv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 13, 40, 37, 881033, tzinfo=utc)),
        ),
    ]
