# Generated by Django 3.0 on 2020-12-18 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_auto_20201218_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='x_pts1',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='x_pts2',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='x_pts3',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='x_pts4',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='x_pts5',
        ),
        migrations.AddField(
            model_name='stat',
            name='name1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='name3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='name4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='name5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='infog',
            name='i_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 14, 17, 9, 429563, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='date_inp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 14, 17, 9, 445166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='searchenter',
            name='d',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 14, 17, 9, 445166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 14, 17, 9, 429563, tzinfo=utc)),
        ),
    ]
