# Generated by Django 3.0.10 on 2021-02-21 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20201218_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infog',
            name='i_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 16, 51, 53, 839123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infog',
            name='image2field',
            field=models.FilePathField(max_length=200, null=True, path='E:\\metricmint project\\metricmint\\media\\images', recursive=True),
        ),
        migrations.AlterField(
            model_name='multiple_images',
            name='date_inp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 16, 51, 53, 839123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='searchenter',
            name='d',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 16, 51, 53, 839123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stat',
            name='s_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 16, 51, 53, 839123, tzinfo=utc)),
        ),
    ]
